
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "@/app/globals.css";
import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer";



const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "The Creative Academy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} antialiased relative `}
      >
        <div className="sticky top-0 z-50">
          <Navbar/>
        </div>
        
          {children}
        
        <Footer/>
      </body>
    </html>
  );
}
